include:
- ./func/*
kind: ArchiveUploadSpec
name: func-vP5T

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-tickets-fn-528967bb-94f0-4f61-9ccf-29bbb0867469
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-user-tickets-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-vP5T
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-01T22:00:13Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-tickets-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-user-tickets-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_user_tickets
    packageref:
      name: get-user-tickets-fn-528967bb-94f0-4f61-9ccf-29bbb0867469
      namespace: default
  requestsPerPod: 1
  resources: {}
