include:
- ./func/*
kind: ArchiveUploadSpec
name: func-dQ4p

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-tickets-fn-93dc33b6-1139-465b-ab81-ed015c005c8f
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-user-tickets-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-dQ4p
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-01-31T19:53:48Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-tickets-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-user-tickets-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.fn
    packageref:
      name: get-user-tickets-fn-93dc33b6-1139-465b-ab81-ed015c005c8f
      namespace: default
  requestsPerPod: 1
  resources: {}
